export const AWS_DYNAMO_TABLES = {
  USER: process.env.AWS_DYNAMODB_USERS_TABLE_NAME,
  PRODUCT: process.env.AWS_DYNAMODB_PRODUCTS_TABLE_NAME,
  BUNDLE: process.env.AWS_DYNAMODB_BUNDLES_TABLE_NAME
};
